### PR TITLE
fix get elements at commit if element was deleted after commit

### LINKED ISSUE #261: Missing check for time of element deletion while getting all elements under commitId
## What is the issue?
There is a case when you are trying to get all the elements from a ref at a specific commit. If the element was deleted after the commit, it will also be missing from the elements request at a earlier commit.

## How to reproduce?
1. Create elements x, y, z
2. Update y, save commit id
3. Delete element x
4. Get elements at step 2 via `/projects/aa/refs/{refId}/elements?commitId={step 2 commit id}`

I believe the check should be happening here

https://github.com/Open-MBEE/exec-mms/blob/adc1e8ca11babc6793a9370c1166cf220e6eb926/crud/src/main/java/org/openmbee/mms/crud/services/NodeGetHelper.java#L131-L133

### PR DESCRIPTION
**Pull request by dlamoris**
Checks if element was deleted before or after requested commit if it's currently deleted and last updated time was before commit.
Added new test collection
fixes #261

### CODE REVIEW

File: crud/src/main/java/org/openmbee/mms/crud/services/NodeGetHelper.java [hunk 1]
```diff
@@ -13,14 +13,24 @@
...
 import org.openmbee.mms.json.ElementJson;
+import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.stereotype.Service;
 
 import static org.openmbee.mms.core.config.ContextHolder.getContext;
 
 @Service
 public class NodeGetHelper extends NodeOperation {
 
+    protected CommitIndexDAO commitIndex;
```
Comment (HuiJun) [inline crud/src/main/java/org/openmbee/mms/crud/services/NodeGetHelper.java:27]: :(

**Review by HuiJun — APPROVED** [review]

File: crud/src/main/java/org/openmbee/mms/crud/services/NodeGetHelper.java (hunk 1 above)
Comment (dlamoris) [reply crud/src/main/java/org/openmbee/mms/crud/services/NodeGetHelper.java:27]: it'll get refactored when we merge in to the boeing branch anyways
